// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3oHJv36VXjO99LBku1OrC6uPpNWioqLQ',
    appId: '1:934699098461:web:052c625dbae520959548b4',
    messagingSenderId: '934699098461',
    projectId: 'flutter-talk-8db27',
    authDomain: 'flutter-talk-8db27.firebaseapp.com',
    storageBucket: 'flutter-talk-8db27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLo2nRjuvrRPMqY1O71QXHRMpLpTw8DCY',
    appId: '1:934699098461:android:a546a1646231fb599548b4',
    messagingSenderId: '934699098461',
    projectId: 'flutter-talk-8db27',
    storageBucket: 'flutter-talk-8db27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUm42ShiBYGn23IZ_wFGTJRC05ZH8pzAk',
    appId: '1:934699098461:ios:32ec581cf1900f549548b4',
    messagingSenderId: '934699098461',
    projectId: 'flutter-talk-8db27',
    storageBucket: 'flutter-talk-8db27.firebasestorage.app',
    iosBundleId: 'com.example.flutterTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3oHJv36VXjO99LBku1OrC6uPpNWioqLQ',
    appId: '1:934699098461:web:a156028df3c633929548b4',
    messagingSenderId: '934699098461',
    projectId: 'flutter-talk-8db27',
    authDomain: 'flutter-talk-8db27.firebaseapp.com',
    storageBucket: 'flutter-talk-8db27.firebasestorage.app',
  );
}
